### ISSUE TITLE
Extend quanteda generics

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#3]
http://stackoverflow.com/questions/31317366/in-r-how-can-i-extend-generic-methods-from-one-package-in-another

**Comment by kbenoit** [comment]
I'd seen that, but I cannot make it work, and this is for S4 anyway.  For S3 it appears to be `@importFrom quanteda docvars` for instance but that does not work either:

When I remove the generic for `dovcars()` from **readtext**, and just include this, it still does not see this method defined for a readtext object.

```r
#' @importFrom quanteda docvars
#' @method docvars readtext
#' @export
docvars.readtext <- function(x, field = NULL) {
    if (!is.null(field))
        warning("field argument not used for docvars on a readtext object", noBreaks. = TRUE)
    as.data.frame(x[, -which(names(x)=="texts"), drop = FALSE])
}
```

UNLESS I also attach **quanteda** , in which case it does work. Maybe this is expected behaviour? I was hoping we could call the function whose generic is defined in quanteda *without* having to attach the whole **quanteda** namespace.

**Comment by adamobeng** [comment]
So that would mean that readtext depends on quanteda? That's ugly (and it should really be the other way around).

**Comment by pnulty** [comment]
I agree that readtext shouldn't depend on quanteda. I think the packages should be as loosely coupled as possible -- if it returns a data.frame, then there might not be a need for a docvars function, users will already know how to access the non-text columns. I think that where possible we should avoid using custom classes and accessor methods, if the package works with base datatypes then the learning curve will be smoother.

**Comment by kbenoit** [comment]
I agree with all this, and suggest we put **quanteda** into `Suggests: ` instead. In **readtext**, we extend the `docvars` and `texts` S3 methods for the readtext object class, but these will only work if **quanteda** is attached. If **quanteda** is not attached, then those methods have no meaning and are not accessible because the generic will not be found. This seems like a consistent and sensible behaviour imho.

However it's not sensible if we want to make a method available for getting the texts or non-text variables out of a readtext object without the **quanteda** framework. But my view is that since it's a data.frame, a user can do this him/herself, knowing that `their_readtext_object[["texts"]]` is always the text, and the rest are other variables.

**Comment by kbenoit** [comment]
Added to quanteda, these extend:  
*  `texts()`  
*  `docnames()`  
*  `ndoc()`  
*  `docvars()`  

These only work when **quanteda** is attached. Only the tests in **readtext** need these.
