### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/readtext#5]

**Comment by adamobeng** [comment]
There are two outstanding problems:
- tests dependent on #9 / #10 
- json tests are broken because of lines 120-126 of readtxt. In particular,

```{r}
readtxt('../data/json/*json', textfield='text')
```

tries to set row.names to

```
[1] "c(\"test.json.1\", \"test.json.2\")"   "c(\"test2.json.1\", \"test2.json.2\")" "test3.json"
```

@kbenoit, do you know why this is?

**Comment by kbenoit** [comment]
Yes, I changed the behaviour from your original code for this, so that if you read in any "single file, multiple-document" format, it names the rows with a serialised version of the filename. (Previously, it errored corpus() because each row had the same name: the common filename.) So if you use wildcards and load more than one file, it needs to serialise each file. I think the same behaviour is present for .csv and .tsv.
